name: Bug report
description: Create a report to help us improve
labels: "bug"

body:
  - type: input
    attributes: 
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. 
        2. 
        ...
    validations:
      required: true
  - type: input
    attributes:
      label: Bonsai Version
      description: | 
        The version of Bonsai that is running. To find the current Bonsai version:
        1. Open the Bonsai editor
        2. Click on Help → About
        3. Note the version number (Version X.Y.Z) here
      placeholder: X.Y.Z
    validations:
      required: true
  - type: input
    attributes:
      label: OpenEphys.Onix1 Version
      description: | 
        The version of the OpenEphys.Onix1 library being used. To find the current library version:
        1. Open the Bonsai package manager
        2. Navigate to the Installed tab
        3. Filter (or scroll down) to OpenEphys.Onix1
        4. Click on the OpenEphys.Onix1 package
        5. Note the version number (Version X.Y.Z) here
      placeholder: X.Y.Z
    validations:
      required: true
  - type: textarea
    attributes:
      label: Attach your workflow
      description: |
        Please attach the workflow in which you encountered the issue below. To do so:
        1. Navigate to the top level of your Bonsai workflow.
        2. Press Ctrl+A to select all nodes.
        3. Press Ctrl+C to copy the workflow as an XML string.
        4. Paste the resulting XML below.
      render: "xml"
    validations:
      required: true
